# ===============================================
#   SendGrid Configuration
# ===============================================
sendgrid.token=![1Q/zcI4NPmvnyDa7Ksclt/sVuI+VqRj5H2mOON0sHA8Gg0nuRrx3VbEJX3G8guPqJKmedirmD7KLwd/fIIO9b/W5Q2YYjQewG94uQvuxiHo=]